### ISSUE TITLE
Adding jar as dependency in POM

### ISSUE THREAD

**Issue by christianpoitras** [compomics/mascotdatfile#12]
Hi,

Is it possible to add mascotdatfile as a dependency for my project in my POM.xml?

If so, can you add that documentation somewhere in the README file?

Thanks.

**Comment by hbarsnes** [comment]
Hi,

The information you need is available in the wiki: https://github.com/compomics/mascotdatfile/wiki/UsageAndExamples#using-mascotdatfile-as-a-maven-dependency. (The current version number is 3.4.32.)

Please let us know if you need more details and we'll reopen the issue.

Best regards,
Harald

**Comment by christianpoitras** [comment]
Thanks! Works like a charm!

**Comment by christianpoitras** [comment]
It works well for versions up to 3.4.19.

Starting from 3.4.20, the dependency psidev.psi.tools:xxindex:0.14 is missing.
  +-com.compomics:mascotdatfile:3.4.32
    +-com.compomics:utilities:4.0.14
      +-uk.ac.ebi.jmzidml:jmzidentml:1.1.9
        +-psidev.psi.tools:xxindex:0.14

**Comment by hbarsnes** [comment]
Hi,

From where do you get the request for xxindex 0.14? 

mascotdatfile should only require xxindex  0.11.

But if you need version 0.14 you can add the following repository:

        <repository>
            <id>ebi-repo</id>
            <name>The EBI Maven2 repository</name>
            <url>http://www.ebi.ac.uk/~maven/m2repo</url>
            <releases>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>

Don't see why you'd need it though..?

Best regards,
Harald

**Comment by christianpoitras** [comment]
I gave the stack from Maven. Basically, it comes from utilities 4.0.14 dependency which depends on jmzidentml version 1.1.9 which depends on xxindex version 0.14.

In the http://genesis.UGent.be/maven2 repository, xxindex is available up to version 0.13, but version 0.14 is not available. This gives me an error.

Here is the stack again.
+-com.compomics:mascotdatfile:3.4.32
+-com.compomics:utilities:4.0.14
+-uk.ac.ebi.jmzidml:jmzidentml:1.1.9
+-psidev.psi.tools:xxindex:0.14

**Comment by hbarsnes** [comment]
Ok, I see what you mean. Did adding the extra repository above to your pom file solve the problem? (At least http://www.ebi.ac.uk/~maven/m2repo does contain the 0.14 version of the missing library.) If so, I will simply add that to the wiki.

**Comment by christianpoitras** [comment]
It works with the EBI repository.

**Comment by hbarsnes** [comment]
Ok, thanks. I've updated the wiki accordingly. Thanks for letting us now about this. I'll now close this issue, but don't hesitate to create a new one if you come across other issues.

I should note that we've mainly moved on to other free search engine alternatives though. See SearchGUI (http://compomics.github.io/projects/searchgui.html) and PeptideShaker (http://compomics.github.io/projects/peptide-shaker.html) for more details.
