### ISSUE TITLE
can not open GUI

### ISSUE THREAD

**Issue by liuyaming1** [compomics/mascotdatfile#16]
I download the jar package from the website<http://compomics.github.io/projects/mascotdatfile.html>
In my win7 computer, when I double click this package, I can not reach the gui, pls help me at any time you
are convenient. I'll be very thankful.
Liu Yaming

**Comment by nielshulstaert** [comment]
Dear Liu,

I assume you want to open the SpectrumViewer; please run java -cp mascotdatfile-3.6.0.jar com.compomics.mascotdatfile.research.tool.spectrumviewer.spectrumviewer_gui.Spectrumviewer_gui from the command line. I've added a section to the wiki page (https://compomics.github.io/projects/mascotdatfile/wiki/usageandexamples.html#running-the-spectrumviewer-graphical-user-interface-gui), thanks for pointing this out.

Best regards,

Niels Hulstaert

**Comment by liuyaming1** [comment]
it works just like you said. Thanks for your help again.
